spring.application.name=SimpleCMS
spring.datasource.url=jdbc:sqlite:simplecms.db
spring.datasource.driver-class-name=org.sqlite.JDBC
PRAGMA foreign_keys = ON;

# Show SQL statements
spring.jdbc.show-sql=true
spring.sql.init.mode=always

# Format SQL nicely
spring.jpa.properties.hibernate.format_sql=true

# Log SQL at DEBUG level
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.springframework.data.jdbc.core=DEBUG
logging.level.org.springframework.data.relational.core.sql=DEBUG
