spring.application.name=SimpleCMS
spring.datasource.url=jdbc:sqlite:simplecms.db
spring.datasource.driver-class-name=org.sqlite.JDBC
PRAGMA foreign_keys = ON;

app.security.username=${USERNAME}
app.security.password=${PASSWORD}
app.jwt.secret=
logging.level.org.springframework.security=DEBUG