spring.application.name=SimpleCMS
spring.datasource.url=jdbc:sqlite:simplecms.db
spring.datasource.driver-class-name=org.sqlite.JDBC
PRAGMA foreign_keys = ON;

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

app.security.username=${USERNAME}
app.security.password=${PASSWORD}
app.jwt.secret=
app.upload-dir=uploads
logging.level.org.springframework.security=DEBUG